language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

matrix:
  include:
    - python: "2.7"
      env: TEST_SUITE=py27
    - python: "3.5"
      env: TEST_SUITE=py35
    - python: "3.6"
      env: TEST_SUITE=py36
    - python: "3.7"
      env: TEST_SUITE=py37
    - python: "3.8"
      env: TEST_SUITE=py38
    - python: "3.9"
      env: TEST_SUITE=py39

install:
  - pip install tox

# command to run tests
script:
  - tox -e pycodestyle,$TEST_SUITE
